### ISSUE TITLE
LinkedIn::OAuthError: invalid_request: missing required parameters

### ISSUE THREAD

**Issue by gotoAndBliss** [emorikawa/linkedin-oauth2#7]
The full error

```
LinkedIn::OAuthError: invalid_request: missing required parameters, includes an invalid parameter value, parameter more than once. : Unable to retrieve access token : appId or redirect uri does not match authorization code or authorization code expired
{"error_description":"missing required parameters, includes an invalid parameter value, parameter more than once. : Unable to retrieve access token : appId or redirect uri does not match authorization code or authorization code expired","error":"invalid_request"}
```

I can reproduce this by doing the following..

``` ruby
url = oauth.auth_code_url
=> "https://www.linkedin.com/uas/oauth2/authorization?client_id=753ksokcpp7c78&raise_errors=true&redirect_uri=https%3A%2F%mywebsite.com&response_type=code&state=WGKZwIh9JQHUnyD86CCp9gqwQRBqN3Vv3wM3BBBhwStvE%3D"
```

I paste this link in my browser, am prompted with the Accept view. I click accept and am redirected successfully back to my website. Per your instructions, I copy the code param out of the URL 

```
https://mywebsite.com/?code=AQQNPhPdXAMnyDS1JF_j5Nxte3mqWXBcoGQQw9RkW19B4dVMQymnDj1wcnQ06BoX3mcILT_wUjFGK8X71TKyLBZOR9UJ56jJl_UGeawUMUnMnXPI2Xg&state=ghfXisaq%2BeI5JDS9ueyKHTGYv%2B67FSfDByIyF%2FVzmeE%3D
```

Which looks like 

``` ruby
code = "AQQNPhPdXAMnyDS1JF_j5Nxte3mqWXBcoGQQw9RkW19B4dVMQymnDj1wcnQ06BoX3mcILT_wUjFGK8X71TKyLBZOR9UJ56jJl_UGeawUMUnMnXPI2Xg"
```

Then I try and complete the request 

``` ruby
 access_token = oauth.get_access_token(code)
```

Which then returns the error above. I'm absolutely doing this in less than 3 to 4 seconds tops.

Any suggestions?

**Comment by jakoss** [comment]
I have exactly same error with linkedin in devise even if i authorize application in like 2-3 seconds. @gotoAndBliss  did you find solution of some type of hack?

**Comment by gotoAndBliss** [comment]
Actually LinkedIn just dropped most of their valuable API support so we
suspended use of it..

On Fri, Oct 23, 2015 at 3:24 PM, Jakub Syty notifications@github.com
wrote:

> I have exactly same error with linkedin in devise even if i authorize
> application in like 2-3 seconds. @gotoAndBliss
> https://github.com/gotoAndBliss did you find solution of some type of
> hack?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/emorikawa/linkedin-oauth2/issues/7#issuecomment-150531592
> .

## 

Daniel Trip Levine
Master Bitmapper Wrapper

**Comment by augnustin** [comment]
> Actually LinkedIn just dropped most of their valuable API

@gotoAndBliss what do you mean? Do you have any reference on this?

Thanks

**Comment by ghost** [comment]
who has a method to kill it,i'm tired now.
